// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANKecGmDcyrMtVP3Ym1egBuHylb79ugZo',
    appId: '1:998526436166:web:1cc37250fd27cc0e251b47',
    messagingSenderId: '998526436166',
    projectId: 'flutter-cloud-firestore-3f80d',
    authDomain: 'flutter-cloud-firestore-3f80d.firebaseapp.com',
    storageBucket: 'flutter-cloud-firestore-3f80d.appspot.com',
    measurementId: 'G-RRER0B7NKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzxHyCUvYFSIc-7TJs_2_rbhSyrBAk9Go',
    appId: '1:998526436166:android:55894effc779e749251b47',
    messagingSenderId: '998526436166',
    projectId: 'flutter-cloud-firestore-3f80d',
    storageBucket: 'flutter-cloud-firestore-3f80d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApYqb5PoM32y56r81nWFq5cnJLuG8N3j0',
    appId: '1:998526436166:ios:ae979aa4503926e8251b47',
    messagingSenderId: '998526436166',
    projectId: 'flutter-cloud-firestore-3f80d',
    storageBucket: 'flutter-cloud-firestore-3f80d.appspot.com',
    iosClientId: '998526436166-p8iv6if22utuvosnv6js6k1homck5g32.apps.googleusercontent.com',
    iosBundleId: 'br.com.alura.flutterCloudFirestore',
  );
}
