// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6EBn3dDwuZrB8cdQ4gZgFdzSPoWtYxQA',
    appId: '1:933267112141:web:d6695e40a55870f94f2984',
    messagingSenderId: '933267112141',
    projectId: 'flutter-cloud-firestore-28135',
    authDomain: 'flutter-cloud-firestore-28135.firebaseapp.com',
    storageBucket: 'flutter-cloud-firestore-28135.appspot.com',
    measurementId: 'G-9ZM0T26M9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqDybQQlF-JTLIzJvllApN8UcY7hy-Vn0',
    appId: '1:933267112141:android:d0468b657337b5a94f2984',
    messagingSenderId: '933267112141',
    projectId: 'flutter-cloud-firestore-28135',
    storageBucket: 'flutter-cloud-firestore-28135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXwgoYBeNBO-7e_1GwHT4UdMjtp-ZiT8',
    appId: '1:933267112141:ios:838243629c69146c4f2984',
    messagingSenderId: '933267112141',
    projectId: 'flutter-cloud-firestore-28135',
    storageBucket: 'flutter-cloud-firestore-28135.appspot.com',
    iosClientId: '933267112141-4j0bhfl5movetbng7aa0t65m5m7eiu6c.apps.googleusercontent.com',
    iosBundleId: 'br.com.alura.flutterCloudFirestore',
  );
}
